config/routes.rb
Rails.application.routes.draw do
  get 'weather/home', to: 'weather#home'

  get 'weather/index', to: 'weather#index'

  root 'weather#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
require 'open_weather'
require 'date'

  def home
  end

  def index
	# @options = { units: "metric", APPID: "randomkey" }
	@x = OpenWeather::Current.geocode(14.651, 121.0486, @options) 

	@coordinates = @x['coord']
	@weather = @x['weather'][0]
	@main = @x['main']
	@wind = @x['wind']
	@sys = @x['sys']
	@sys['sunrise'] = Time.at(@sys['sunrise'])
	@sys['sunset'] = Time.at(@sys['sunset'])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Capstone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/home.html.erb
<div class="ui grid">
	<div class="one wide row">
	</div>
</div>
	<h1 class="ui center aligned icon header">
	  <i class="circular cloud icon"></i>
	  Smart Blinds
	</h1>
	<h4 class="ui center aligned header">
		A Web Server for Smart Blinds
	</h4>
	<div class="ui center aligned container">
	  <%= link_to "Get current weather", weather_index_path, id: "button", class: "ui blue button" %>
	</div>

app/views/weather/index.html.erb
<div class="ui grid">
	<div class ="one wide row">
	</div>
	<div class="ui center aligned container">
		<h2 class="ui center aligned icon header">
		  <i class="circular cloud icon"></i>
		  <div class="content">
		  Quezon City, Philippines
			  <div class="ui sub header">
			  <%= render html: "(#{@coordinates['lon']}, #{@coordinates['lat']})".html_safe %>
			  <div>
		  </div>
		</h2>
	</div>
	<div class ="one wide row">
	</div>
	<div class = "four wide row">
	<div class="four wide column">
	</div>
	<div class="five wide column">
		<div class="ui stackable container segment">
			<h2 class="ui center aligned icon header">
			  <i class="thermometer three quarters icon"></i>
			  <div class="content">
			  <%= render html: "#{@main['temp']}°C".html_safe %>
			  </div>
			  	<div class="ui sub header">
				  <%= render html: "min: #{@main['temp_min']}°C, max: #{@main['temp_max']}°C".html_safe %>
				</div>
			</h2>
			<div class="ui divider"></div>
			<h2 class="ui center aligned header">
			  <div class="content">
			  <%= render html: "#{@weather['main']}".html_safe %>
				  <div class="ui sub header">
				  <%= render html: "#{@weather['description']}".html_safe %>
				  </div>
			  </div>
			</h2>
			<div class="content"><%= render html: "Pressure: #{@main['pressure']} Pa".html_safe %></div>
			<div class="content"><%= render html: "Humidity: #{@main['humidity']} g/m^3".html_safe %></div>
			<div class="content"><%= render html: "Wind speed: #{@wind['speed']} kph".html_safe %></div>
		</div>
	</div>
	<div class="three wide column">
		<div class="ui container segment">
			<h2 class="ui center aligned icon header">
			  <i class="sun icon"></i>
			  <div class="content">
			  Sunrise
				  <div class="ui sub header">
				  <%= render html: "#{@sys['sunrise']}".html_safe %>
				  </div>
			  </div>
			</h2>
			<h2 class="ui center aligned icon header">
			  <i class="moon icon"></i>
			  <div class="content">
			  Sunset
				  <div class="ui sub header">
				  <%= render html: "#{@sys['sunset']}".html_safe %>
				  </div>
			  </div>
			</h2>
		</div>
	</div>
	<div class="four wide column">
	</div>
	</div>
	<div class ="one wide row">
	</div>
</div>

<script>
	setTimeout("location.reload();",899999);
</script>